theme: minima
title: Matrix
author: Tyrone Nickle
email: yredpill@domain.com
description: > # this means to ignore newlines until "baseurl:"
 lets explore the innermost workings of your inner most thoughts

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
